### ISSUE TITLE
base image 를 kmubigdata 에서 생성

### ISSUE THREAD

**Issue by hyu-leeky** [kmubigdata/ubuntu-hadoop#1]
현재 베이스 이미지가 외부 리포지토리로 되어있는데,
베이스 이미지도 로컬버전 (kmubigdata) 로 바꿔주는게 좋을듯
https://github.com/kmubigdata/ubuntu-hadoop/blob/master/Dockerfile#L1

**Comment by KimJeongChul** [comment]
성수학생에게 질문하여 Dockerfile을 받고 DockerHub, GitHub에 작성하여 이미지 빌드하였습니다.
https://github.com/kmubigdata/ubuntu-hadoop/issues
https://github.com/kmubigdata/ubuntu-1604

**Comment by KimJeongChul** [comment]
성수학생에게 질문하여 Dockerfile을 받고 DockerHub, GitHub에 작성하여 이미지 빌드하였습니다.
https://hub.docker.com/r/kmubigdata/ubuntu-1604/
https://github.com/kmubigdata/ubuntu-1604

**Comment by hyu-leeky** [comment]
good job!
