### ISSUE TITLE
이미지 빌드시에 dependency 가 어떻게 반영되는지 확인 필요

### ISSUE THREAD

**Issue by hyu-leeky** [kmubigdata/ubuntu-hadoop#2]
#1 에서 베이스 이미지를 kmubigdata ubuntu 로 업데이트 후 종속된 다커 이미지 (ubuntu-spark) 도 자동으로 빌드 되는지 확인 필요

**Comment by KimJeongChul** [comment]
docker sungsu7437 pull -> push 후 확인하여 체크.

**Comment by hyu-leeky** [comment]
만약 ubuntu-hadoop 업데이트 후 자동으로 ubuntu-spark 가 자동으로 빌드 되지는 않는다면 어떤 방식으로 ubuntu-spark 를 빌드 하는지 확인 필요.

**Comment by hyu-leeky** [comment]
docker push 를 했을때 다커 허브로 올라가는 이미지가 Dockerfile 의 기반만 되는지,  아니면 docker 이미지에 바로 작업후 cmmit 한 이미지가 올라가는지 확인 필요.

**Comment by hyu-leeky** [comment]
![image](https://cloud.githubusercontent.com/assets/17699616/26101201/411a2e9c-3a6b-11e7-9a75-426131477e9e.png)

다커허브에 리포지토리를 링크하는 기능이 있어서, 자동 빌드가 가능해보임. BuildSetting 메뉴.
